apiVersion: v1
kind: Service
metadata:
  name: neuralguard
  namespace: neuralguard
  labels:
    app.kubernetes.io/name: neuralguard
    app.kubernetes.io/part-of: neuralguard-appliance
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: neuralguard
  ports:
    - port: 8000
      targetPort: http
      name: http